I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 352, in script
    show screen credits
  File "renpy/common/000statements.rpy", line 647, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen credits is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 352, in script
    show screen credits
  File "/Users/esmenadeau/Desktop/renpy-8.2.3-sdk/renpy/ast.py", line 1971, in execute
    self.call("execute")
  File "/Users/esmenadeau/Desktop/renpy-8.2.3-sdk/renpy/ast.py", line 1953, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Users/esmenadeau/Desktop/renpy-8.2.3-sdk/renpy/statements.py", line 349, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 647, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "/Users/esmenadeau/Desktop/renpy-8.2.3-sdk/renpy/display/screen.py", line 1322, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen credits is not known.


macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.2.3.24061702
Two in the Morning 1.0
Sun Dec  1 19:21:00 2024
